### PR TITLE
Tidy up npm dependancies

### PR DESCRIPTION
**Pull request by davecarlson**
Pretty straight forward this one:
- remove pretty-ms as you don't use it anymore
- add support for react 15
- update to latest moment

### CODE REVIEW

**Comment by davecarlson** [comment]
Updated to also clean up timeSeparator

**Comment by davecarlson** [comment]
WDYT ?

**Comment by davecarlson** [comment]
Hi, can this be merged ?

**Comment by davecarlson** [comment]
Updated with even more changes

**Comment by sungwoncho** [comment]
@davecarlson sorry for the delay. I see that you rewrote method shorthands into arrow functions:

```
componentDidMount()

componentDidMount = ({}) => {
...
```

Any reasons for this?

**Comment by davecarlson** [comment]
Yes , it fixed a bug with react 15 where it would error if you remounted a
component
On Sun, 29 May 2016 at 03:22, Sung Won Cho notifications@github.com wrote:

> @davecarlson https://github.com/davecarlson sorry for the delay. I see
> that you rewrote method shorthands into arrow functions:
> 
> componentDidMount()
> 
> componentDidMount = ({}) => {
> ...
> 
> Any reasons for this?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/sungwoncho/react-cntdwn/pull/3#issuecomment-222338989,
> or mute the thread
> https://github.com/notifications/unsubscribe/AASStp9wDoiRepUH3Y-yk9DaUqS1a3ENks5qGPhNgaJpZM4IGFFA
> .

## 

_Fast Web Media Ltd, Digital World Centre, 1 Lowry Plaza, Media City, 
Manchester. M50 3UB_
_PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS E-MAIL_
This e-mail is intended solely for the addressee and is strictly 
confidential. If you are not the addressee, please do not read, print, 
re-transmit, store or act in reliance on it or any attachments. Instead 
please e-mail it back to the sender and delete the message from your 
computer. Fast Web Media accepts no liability for changes made to this 
e-mail (and any attachments) after it was sent or for viruses arising as a 
result of this e-mail transmission. Any unauthorised reproduction, 
dissemination, copying, disclosure, modification, distribution and/or 
publication of this e-mail message is strictly prohibited. Fast Web Media 
reserve the right to monitor all e-mail communications through its networks.
Fast Web Media Ltd is registered in England with Company Number - 2946537, 
the Registered Office is c/o Haines Watts, 1st Floor, Northern Assurance 
Buildings, Albert Square, 9/21 Princess Street, Manchester, M2 4DN. Part of 
mporium Group PLC

##

**Comment by sungwoncho** [comment]
What was the error, and how does this fix it? Any references to a styleguide mentioning this in React 0.15?

**Comment by davecarlson** [comment]
Cannot setstate in a mounted component
On Sun, 29 May 2016 at 06:50, Sung Won Cho notifications@github.com wrote:

> What was the error, and how does this fix it? Any references to a
> styleguide mentioning this in React 0.15?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/sungwoncho/react-cntdwn/pull/3#issuecomment-222344208,
> or mute the thread
> https://github.com/notifications/unsubscribe/AASStshas6g3SwJQKJaZLuKHtNFxsVz4ks5qGSkWgaJpZM4IGFFA
> .

## 

_Fast Web Media Ltd, Digital World Centre, 1 Lowry Plaza, Media City, 
Manchester. M50 3UB_
_PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS E-MAIL_
This e-mail is intended solely for the addressee and is strictly 
confidential. If you are not the addressee, please do not read, print, 
re-transmit, store or act in reliance on it or any attachments. Instead 
please e-mail it back to the sender and delete the message from your 
computer. Fast Web Media accepts no liability for changes made to this 
e-mail (and any attachments) after it was sent or for viruses arising as a 
result of this e-mail transmission. Any unauthorised reproduction, 
dissemination, copying, disclosure, modification, distribution and/or 
publication of this e-mail message is strictly prohibited. Fast Web Media 
reserve the right to monitor all e-mail communications through its networks.
Fast Web Media Ltd is registered in England with Company Number - 2946537, 
the Registered Office is c/o Haines Watts, 1st Floor, Northern Assurance 
Buildings, Albert Square, 9/21 Princess Street, Manchester, M2 4DN. Part of 
mporium Group PLC

##

**Comment by davecarlson** [comment]
Basically, if you use arrow functions, you get access to the parent this,
rather than the internal Functions this instead
On Sun, 29 May 2016 at 07:00, Dave Carlson dave.carlson@fastwebmedia.com
wrote:

> Cannot setstate in a mounted component
> On Sun, 29 May 2016 at 06:50, Sung Won Cho notifications@github.com
> wrote:
> 
> > What was the error, and how does this fix it? Any references to a
> > styleguide mentioning this in React 0.15?
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > https://github.com/sungwoncho/react-cntdwn/pull/3#issuecomment-222344208,
> > or mute the thread
> > https://github.com/notifications/unsubscribe/AASStshas6g3SwJQKJaZLuKHtNFxsVz4ks5qGSkWgaJpZM4IGFFA
> > .

## 

_Fast Web Media Ltd, Digital World Centre, 1 Lowry Plaza, Media City, 
Manchester. M50 3UB_
_PLEASE CONSIDER THE ENVIRONMENT BEFORE PRINTING THIS E-MAIL_
This e-mail is intended solely for the addressee and is strictly 
confidential. If you are not the addressee, please do not read, print, 
re-transmit, store or act in reliance on it or any attachments. Instead 
please e-mail it back to the sender and delete the message from your 
computer. Fast Web Media accepts no liability for changes made to this 
e-mail (and any attachments) after it was sent or for viruses arising as a 
result of this e-mail transmission. Any unauthorised reproduction, 
dissemination, copying, disclosure, modification, distribution and/or 
publication of this e-mail message is strictly prohibited. Fast Web Media 
reserve the right to monitor all e-mail communications through its networks.
Fast Web Media Ltd is registered in England with Company Number - 2946537, 
the Registered Office is c/o Haines Watts, 1st Floor, Northern Assurance 
Buildings, Albert Square, 9/21 Princess Street, Manchester, M2 4DN. Part of 
mporium Group PLC

##

**Comment by sungwoncho** [comment]
If I understand correctly, the arrow functions were added because React does not automatically bind `this` for the components anymore. But I've never seen component methods written this way. I'd prefer doing `.bind(this)` or `.call(this)` unless there is an official styleguide for doing this.

**Comment by kikill95** [comment]
@sungwoncho time to merge it

**Comment by sungwoncho** [comment]
@davecarlson thanks. also added you on npm in case you want to release.

**Pull request merged**
